# Labeler configuration (v5+ match object format)
# Uses existing labels in the repo to avoid permission errors on PR runs

documentation:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.md'
    - 'MasterPlan.md'
    - 'PRODUCTION_DEPLOYMENT_RUNBOOK.md'
    - 'COMPREHENSIVE_PHASE_COUNT_ANALYSIS.md'

testing:
- changed-files:
  - any-glob-to-any-file:
    - '.github/workflows/**'
    - '.github/labeler.yml'

infrastructure:
- changed-files:
  - any-glob-to-any-file:
    - 'deploy/**'
    - 'docker/**'
    - 'triage/**'

enhancement:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.py'
    - '**/*.sh'
