name: Phase Gap - Missing Phase Implementation
description: Use this template to request implementation or triage of a missing phase identified by the Phase Audit workflow.
title: "[Phase Gap] Implement/Triage Phase {{phase-number}}"
labels: ["phase-gap", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Phase Gap Triage Request**

  - type: input
    id: phase-number
    attributes:
      label: "Phase Number"
      description: "The phase number that is missing (e.g., 18, 28-31)."
      placeholder: "e.g., 18"

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Describe what's required to implement the phase or why it can be intentionally omitted. Include references to `COMPREHENSIVE_PHASE_COUNT_ANALYSIS.md` and related files."

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Select an appropriate priority for this phase gap"
      options:
        - "low"
        - "medium"
        - "high"
